language: node_js
node_js:
- 6
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
env:
  global:
    - DISPLAY=:99
before_install:
- rm -rf node_modules
before_script:
- npm install grunt-cli -g
- npm install bower -g
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm test
- npm run frisby
- npm run protractor
